name: Segundo CI-CD
on:
  push:
    branch: ["main"]
  workflow_dispatch:
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - name: Obtendo Código
      uses: actions/checkout@v4.2.2
    - name: Login to Docker Hub
      uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      
        
      
      

